print "Tuesday: Cloudy, High 46, Low 32"
print "Wednesday: Partly Cloudy, High 46, Low 32"
print "Thursday: Rainy, High, 48, Low 32"
print "Friday: Cloudy, High 31, Low 22"
print "Saturday: Partly Cloudy, High 42, Low 34"
print "Sunday: Rain, High 47, Low 36"
print "Monday: Partly Cloudy, High 46, low 36"